2020-08-11 11:33:03: info: Lich 4.6.58
2020-08-11 11:33:03: info: Ruby 2.5.5
2020-08-11 11:33:03: info: i386-mingw32
2020-08-11 11:33:03: info: no force-mode info given
2020-08-11 11:33:03: error in Gtk.queue: Couldn’t recognize the image file format for file “fly64.png”
	C:/Ruby4Lich/lib/ruby/gems/2.5.0/gems/gobject-introspection-3.2.9-x86-mingw32/lib/gobject-introspection/loader.rb:317:in `invoke'
	C:/Ruby4Lich/lib/ruby/gems/2.5.0/gems/gobject-introspection-3.2.9-x86-mingw32/lib/gobject-introspection/loader.rb:317:in `block (2 levels) in load_constructor_infos'
	C:/Ruby4Lich/lib/ruby/gems/2.5.0/gems/gdk_pixbuf2-3.2.9-x86-mingw32/lib/gdk_pixbuf2/pixbuf.rb:115:in `initialize_with_hash'
	C:/Ruby4Lich/lib/ruby/gems/2.5.0/gems/gdk_pixbuf2-3.2.9-x86-mingw32/lib/gdk_pixbuf2/pixbuf.rb:26:in `initialize'
	C:/Ruby4Lich/lib/ruby/gems/2.5.0/gems/gdk_pixbuf2-3.2.9-x86-mingw32/lib/gdk_pixbuf2/deprecated.rb:45:in `new'
	C:/Ruby4Lich/lib/ruby/gems/2.5.0/gems/gdk_pixbuf2-3.2.9-x86-mingw32/lib/gdk_pixbuf2/deprecated.rb:45:in `new'
	D:/Google Drive/Software/GemstoneIV/GemstoneIV LICH/lich/lich.rbw:10730:in `block in <main>'
	D:/Google Drive/Software/GemstoneIV/GemstoneIV LICH/lich/lich.rbw:620:in `block in queue'
	D:/Google Drive/Software/GemstoneIV/GemstoneIV LICH/lich/lich.rbw:12718:in `main'
	D:/Google Drive/Software/GemstoneIV/GemstoneIV LICH/lich/lich.rbw:12718:in `<main>'
#<Thread:0x06d3e5d0@D:/Google Drive/Software/GemstoneIV/GemstoneIV LICH/lich/lich.rbw:10737 run> terminated with exception (report_on_exception is true):
D:/Google Drive/Software/GemstoneIV/GemstoneIV LICH/lich/lich.rbw:12055:in `kill': wrong number of arguments (given 0, expected 1) (ArgumentError)
	from D:/Google Drive/Software/GemstoneIV/GemstoneIV LICH/lich/lich.rbw:12055:in `block in <main>'
